name: CI Testing
on:
  push:
    branches:
      - "master"
  pull_request:
jobs:
  component-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          install: true
          command: yarn cypress run-ct
