name: Publish package

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: [published]

jobs:
  build-package:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install env.
        run: |
          yarn install
          yarn husky install

      - name: Build UI
        run: yarn build
      - run: ls -lh build/
      - name: Pack UI
        working-directory: build/
        run: zip ../v0.0.0.zip -r .
      - run: ls -lh .

      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ github.sha }}
          path: "*.zip"

  upload-package:
    runs-on: ubuntu-20.04
    needs: build-package
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}
      - run: ls -lh .
      - name: Upload to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "*.zip"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  publish-package:
    runs-on: ubuntu-20.04
    needs: build-package
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master' # FIXME
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}
      - run: ls -lh .

      - name: Upload build to S3
        working-directory: ${{ env.legacy_dir }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUB_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PUB_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          pip install -q awscli
          aws s3 cp *.zip s3:/lightning-packages/ui/ --acl public-read
